day4
KhasanMeliev/problem_solving pull request #1
Opened 2022-04-27 06:14 UTC by KhasanMeliev

2022-04-27 15:01 UTC, javokhirm commented on Day4/day4.js
> +// function compareArrays(arr1, arr2) {
Try to use another algorithm for this problem

2022-04-27 15:01 UTC, javokhirm commented on Day4/day4.js
> +// let add = (user["hobby"] = "coding");
Why we need let add = ?

2022-04-27 15:04 UTC, javokhirm requested changes
Fix problems according to comments

2022-04-28 04:27 UTC, merged

2022-10-11 09:20 UTC, KhasanMeliev commented
Add qowayabman key/value wuning ucun wunaqa yozgandim

On Wed, Apr 27, 2022, 8:01 PM Javokhir Meliev ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In Day4/day4.js
> <https://github.com/KhasanMeliev/problem_solving/pull/1#discussion_r859911684>
> :
>
> > +//   age: 13,
> +//   hobby: "coding",
> +// };
> +// let checkKey = "name" in user;
> +// if (checkKey) {
> +//   console.log("key exists");
> +// } else {
> +//   console.log("key doesn't exists");
> +// }
> +
> +//------------------------- Add Key/Value Pair to an Object---------------
> +// let user = {
> +//   name: "hasan",
> +//   age: 13,
> +// };
> +// let add = (user["hobby"] = "coding");
>
> Why we need let add = ?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/KhasanMeliev/problem_solving/pull/1#pullrequestreview-955064159>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUHPKWHHG5AU3RWMRT4KI4DVHFJFRANCNFSM5UN755SQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>